[package]
name = "metalforge-lib"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
crossbeam-channel = "0.5"
rodio = { version = "0.21", default-features = false, features = [ "playback", "lewton", "wav" ] }
